-- Insert demo users (these will be created after auth signup)
-- Note: The actual user IDs will be generated by Supabase Auth
-- This is just for reference of the demo accounts structure

-- Demo data for broadcast reports (will be inserted after users are created)
-- This script will be run after the authentication system is set up
