-- Insert demo users after they sign up through the auth system
-- This script should be run after the demo accounts are created via Supabase Auth

-- Note: These UUIDs should match the actual user IDs created by Supabase Auth
-- For demo purposes, we'll create placeholder entries that can be updated later

-- Demo users data (to be inserted after auth signup)
-- bagus@tvri.com - Admin
-- alan@tvri.com - Operator  
-- hafiz@tvri.com - Operator

-- This script will be executed manually after the auth users are created
-- The actual user IDs will be generated by Supabase Auth during signup
